Category model
wJoenn/rentart pull request #38
Opened 2023-02-17 19:25 UTC by Glod33

2023-02-17 19:36 UTC, wJoenn approved these changes

2023-02-17 22:12 UTC, wJoenn requested changes
I just noticed the schema.rb isn't in here.
That means the migration file hasn't been migrated and the schema hasn't been updated.

Can you migrate your migration file then make a new commit with the updated schema ?

2023-02-18 09:12 UTC, MarianaCarlota approved these changes

2023-02-18 14:08 UTC, wJoenn approved these changes

2023-02-18 14:15 UTC, merged