navbar dropdown
wJoenn/rentart pull request #60
Opened 2023-02-21 19:12 UTC by MarianaCarlota

![image](https://user-images.githubusercontent.com/114437310/220437223-96047f9c-38c0-41e8-b8f9-18932cbfa973.png)

2023-02-21 19:55 UTC, wJoenn approved these changes

2023-02-21 19:55 UTC, wJoenn commented on package.json
> +    "autoprefixer": "^9",
Can you remove this line

2023-02-21 19:55 UTC, wJoenn commented on package.json
> +    "tailwindcss": "npm:@tailwindcss/postcss7-compat",
these 3 lines

2023-02-21 19:55 UTC, wJoenn commented on package.json
>    }
And these 3 lines please ?

2023-02-21 19:55 UTC, wJoenn commented on app/views/shared/_navbar.html.erb
> +        <div class="options" role="menu" aria-orientation="vertical">
Can you remove the aria-orientation dataset ? You don't need it anymore

2023-02-21 19:55 UTC, wJoenn commented on app/views/shared/_navbar.html.erb
> +          <%= link_to "See all pieces of art", arts_path, role: "menuitem", class: "option" %>
You don't need the role anymore too so it can be removed

2023-02-21 19:55 UTC, wJoenn commented on app/views/shared/_navbar.html.erb
> +          </button>
There's no reason to have a link inside a button
Remove the button element and just keep the if else with the links inside.
The you can give the btn-default class and the btn-gold class to both link_to
to log_out use turbo-method: :delete in the link_to

2023-02-21 19:55 UTC, wJoenn commented on app/javascript/controllers/dropdown_menu_controller.js
> +import {enter, leave, toggle} from 'el-transition';
You can delete this line

2023-02-21 19:55 UTC, wJoenn commented on app/javascript/controllers/dropdown_menu_controller.js
> +console.log("hello from dropdown controller");
You can delete this too

2023-02-21 19:55 UTC, wJoenn commented on app/javascript/controllers/dropdown_menu_controller.js
> +  }
We're not using the connect method so let's get rid of it for now

2023-02-21 19:55 UTC, wJoenn commented on app/javascript/controllers/dropdown_menu_controller.js
> +}
You can remove the if else statement and just toggle the class "hidden" on click

2023-02-21 19:55 UTC, wJoenn commented on app/assets/stylesheets/config/_colors.scss
> +$lightgrey: #d3d3d3;
This can be removed

2023-02-21 19:55 UTC, wJoenn commented on app/assets/stylesheets/components/_navbar.scss
> +  width: 95%;
padding would make more sense

2023-02-23 15:39 UTC, Glod33 approved these changes

2023-02-23 15:42 UTC, wJoenn requested changes
Review planned for tonight

2023-02-23 19:39 UTC, wJoenn approved these changes

2023-02-23 19:39 UTC, merged